name: initial_workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  initial_run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: print python version
        run: |
          python --version